//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace CardScraperLinq
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CardContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new mtgpeertrader_testEntities object using the connection string found in the 'mtgpeertrader_testEntities' section of the application configuration file.
        /// </summary>
        public CardContext() : base("name=mtgpeertrader_testEntities", "mtgpeertrader_testEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new mtgpeertrader_testEntities object.
        /// </summary>
        public CardContext(string connectionString) : base(connectionString, "mtgpeertrader_testEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new mtgpeertrader_testEntities object.
        /// </summary>
        public CardContext(EntityConnection connection) : base(connection, "mtgpeertrader_testEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<magiccard> magiccards
        {
            get
            {
                if ((_magiccards == null))
                {
                    _magiccards = base.CreateObjectSet<magiccard>("magiccards");
                }
                return _magiccards;
            }
        }
        private ObjectSet<magiccard> _magiccards;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the magiccards EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomagiccards(magiccard magiccard)
        {
            base.AddObject("magiccards", magiccard);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mtgpeertrader_testModel", Name="magiccard")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class magiccard : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new magiccard object.
        /// </summary>
        /// <param name="idMagicCards">Initial value of the IdMagicCards property.</param>
        /// <param name="fk_IdMagicCardExpansion">Initial value of the fk_IdMagicCardExpansion property.</param>
        /// <param name="cardName">Initial value of the CardName property.</param>
        public static magiccard Createmagiccard(global::System.Int32 idMagicCards, global::System.SByte fk_IdMagicCardExpansion, global::System.String cardName)
        {
            magiccard magiccard = new magiccard();
            magiccard.IdMagicCards = idMagicCards;
            magiccard.fk_IdMagicCardExpansion = fk_IdMagicCardExpansion;
            magiccard.CardName = cardName;
            return magiccard;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdMagicCards
        {
            get
            {
                return _IdMagicCards;
            }
            set
            {
                if (_IdMagicCards != value)
                {
                    OnIdMagicCardsChanging(value);
                    ReportPropertyChanging("IdMagicCards");
                    _IdMagicCards = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdMagicCards");
                    OnIdMagicCardsChanged();
                }
            }
        }
        private global::System.Int32 _IdMagicCards;
        partial void OnIdMagicCardsChanging(global::System.Int32 value);
        partial void OnIdMagicCardsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.SByte fk_IdMagicCardExpansion
        {
            get
            {
                return _fk_IdMagicCardExpansion;
            }
            set
            {
                Onfk_IdMagicCardExpansionChanging(value);
                ReportPropertyChanging("fk_IdMagicCardExpansion");
                _fk_IdMagicCardExpansion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fk_IdMagicCardExpansion");
                Onfk_IdMagicCardExpansionChanged();
            }
        }
        private global::System.SByte _fk_IdMagicCardExpansion;
        partial void Onfk_IdMagicCardExpansionChanging(global::System.SByte value);
        partial void Onfk_IdMagicCardExpansionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CardName
        {
            get
            {
                return _CardName;
            }
            set
            {
                OnCardNameChanging(value);
                ReportPropertyChanging("CardName");
                _CardName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CardName");
                OnCardNameChanged();
            }
        }
        private global::System.String _CardName;
        partial void OnCardNameChanging(global::System.String value);
        partial void OnCardNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ManaCost
        {
            get
            {
                return _ManaCost;
            }
            set
            {
                OnManaCostChanging(value);
                ReportPropertyChanging("ManaCost");
                _ManaCost = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ManaCost");
                OnManaCostChanged();
            }
        }
        private global::System.String _ManaCost;
        partial void OnManaCostChanging(global::System.String value);
        partial void OnManaCostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.SByte> ConvertedManaCost
        {
            get
            {
                return _ConvertedManaCost;
            }
            set
            {
                OnConvertedManaCostChanging(value);
                ReportPropertyChanging("ConvertedManaCost");
                _ConvertedManaCost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConvertedManaCost");
                OnConvertedManaCostChanged();
            }
        }
        private Nullable<global::System.SByte> _ConvertedManaCost;
        partial void OnConvertedManaCostChanging(Nullable<global::System.SByte> value);
        partial void OnConvertedManaCostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Types
        {
            get
            {
                return _Types;
            }
            set
            {
                OnTypesChanging(value);
                ReportPropertyChanging("Types");
                _Types = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Types");
                OnTypesChanged();
            }
        }
        private global::System.String _Types;
        partial void OnTypesChanging(global::System.String value);
        partial void OnTypesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CardText
        {
            get
            {
                return _CardText;
            }
            set
            {
                OnCardTextChanging(value);
                ReportPropertyChanging("CardText");
                _CardText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CardText");
                OnCardTextChanged();
            }
        }
        private global::System.String _CardText;
        partial void OnCardTextChanging(global::System.String value);
        partial void OnCardTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FlavorText
        {
            get
            {
                return _FlavorText;
            }
            set
            {
                OnFlavorTextChanging(value);
                ReportPropertyChanging("FlavorText");
                _FlavorText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FlavorText");
                OnFlavorTextChanged();
            }
        }
        private global::System.String _FlavorText;
        partial void OnFlavorTextChanging(global::System.String value);
        partial void OnFlavorTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PT
        {
            get
            {
                return _PT;
            }
            set
            {
                OnPTChanging(value);
                ReportPropertyChanging("PT");
                _PT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PT");
                OnPTChanged();
            }
        }
        private global::System.String _PT;
        partial void OnPTChanging(global::System.String value);
        partial void OnPTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Loyalty
        {
            get
            {
                return _Loyalty;
            }
            set
            {
                OnLoyaltyChanging(value);
                ReportPropertyChanging("Loyalty");
                _Loyalty = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Loyalty");
                OnLoyaltyChanged();
            }
        }
        private global::System.String _Loyalty;
        partial void OnLoyaltyChanging(global::System.String value);
        partial void OnLoyaltyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Rarity
        {
            get
            {
                return _Rarity;
            }
            set
            {
                OnRarityChanging(value);
                ReportPropertyChanging("Rarity");
                _Rarity = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Rarity");
                OnRarityChanged();
            }
        }
        private global::System.String _Rarity;
        partial void OnRarityChanging(global::System.String value);
        partial void OnRarityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CardNumber
        {
            get
            {
                return _CardNumber;
            }
            set
            {
                OnCardNumberChanging(value);
                ReportPropertyChanging("CardNumber");
                _CardNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CardNumber");
                OnCardNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _CardNumber;
        partial void OnCardNumberChanging(Nullable<global::System.Int32> value);
        partial void OnCardNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Artist
        {
            get
            {
                return _Artist;
            }
            set
            {
                OnArtistChanging(value);
                ReportPropertyChanging("Artist");
                _Artist = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Artist");
                OnArtistChanged();
            }
        }
        private global::System.String _Artist;
        partial void OnArtistChanging(global::System.String value);
        partial void OnArtistChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GathererMultiverseID
        {
            get
            {
                return _GathererMultiverseID;
            }
            set
            {
                OnGathererMultiverseIDChanging(value);
                ReportPropertyChanging("GathererMultiverseID");
                _GathererMultiverseID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GathererMultiverseID");
                OnGathererMultiverseIDChanged();
            }
        }
        private Nullable<global::System.Int32> _GathererMultiverseID;
        partial void OnGathererMultiverseIDChanging(Nullable<global::System.Int32> value);
        partial void OnGathererMultiverseIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.SByte> Variation
        {
            get
            {
                return _Variation;
            }
            set
            {
                OnVariationChanging(value);
                ReportPropertyChanging("Variation");
                _Variation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Variation");
                OnVariationChanged();
            }
        }
        private Nullable<global::System.SByte> _Variation;
        partial void OnVariationChanging(Nullable<global::System.SByte> value);
        partial void OnVariationChanged();

        #endregion
    
    }

    #endregion
    
}
